spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bidaydb
    username: root
    password: biday
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080


payments:
  toss:
    secret:
      key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6


