services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./mysql/biday/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mysql/biday/var/lib/mysql:/var/lib/mysql
      - ./mysql/biday/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=bidaydb
      - MYSQL_ROOT_PASSWORD=biday
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    restart: always

  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/bidaydb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=biday
      - MONGO_INITDB_DATABASE=bidaydb
    restart: always
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --requirepass password
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: bidy
      POSTGRES_DB: biday
    restart: always